name: Update Notion Stocks

on:
  schedule:
    - cron: "0 1 * * *"  # 09:00 Asia/Hong_Kong
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir "notion-client==2.2.1" yfinance pandas
          python -c "import importlib.metadata as m; print('notion-client version:', m.version('notion-client'))"
     
      - name: Run updater
        run: python update_stocks.py
        env:
          NOTION_TOKEN: $ secrets.NOTION_TOKEN 
          NOTION_DATA_SOURCE_URL: "https://www.notion.so/44ee4ae984ab81ffbb2d000302eb5600/ds/76fadc188de949aa875d051f4a1f6cf1?db=5334cda0444943b196bee4bcd430fe81&source=copy_link"
